# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c351be8a4a5ff49090ad05c1def75d972f5c311a50edb3d0d672a4e56540ca30b554a8357b3463b7eadced9ebdf41030381e7b8623f344bee0cc29e9d191cf5c

test:
  secret_key_base: d3d0e2a332af10c7823ed667b9153b1034d63f55bb3198d64ffa89751be7c8b38663bd5e0c848c2bad65b3d7216b4d48b1b96169aaf13bed0834efebbc57251a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
